name: aws_auth
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: "<1.0.0"
  amplify_core: '<1.0.0'
  amplify_api: "<1.0.0"
  amplify_datastore: "<1.0.0"
  amplify_auth_cognito: "<1.0.0"
  flutter_bloc:

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
